version: '3.8'

services:
  node1:
    build: .
    hostname: node1
    ports:
      - "8000:8000"
    environment:
      - NODE_ID=node1
      - HOST=0.0.0.0
      - PORT=8000
      - WAL_DIR=/app/wal
    volumes:
      - node1_wal:/app/wal
    networks:
      - cache_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  node2:
    build: .
    hostname: node2
    ports:
      - "8001:8000"
    environment:
      - NODE_ID=node2
      - HOST=0.0.0.0
      - PORT=8000
      - WAL_DIR=/app/wal
    volumes:
      - node2_wal:/app/wal
    networks:
      - cache_net
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  node3:
    build: .
    hostname: node3
    ports:
      - "8002:8000"
    environment:
      - NODE_ID=node3
      - HOST=0.0.0.0
      - PORT=8000
      - WAL_DIR=/app/wal
    volumes:
      - node3_wal:/app/wal
    networks:
      - cache_net
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  cache_net:
    driver: bridge

volumes:
  node1_wal:
  node2_wal:
  node3_wal: 